[book]
authors = ["Mina329"]
language = "en"
multilingual = false
src = "src"
title = "QA Exercises"
[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
google-analytics = "G-Q0R6TK9CN5"
